services:
  quote-service:
    image: quote-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      QUOTE_READER_USERNAME: ${QUOTE_READER_USER}
      QUOTE_READER_PASSWORD: ${QUOTE_READER_PASSWORD}
      QUOTE_ADMIN_USERNAME: ${QUOTE_ADMIN_USER}
      QUOTE_ADMIN_PASSWORD: ${QUOTE_ADMIN_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quotesdb
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: